# Losely based on the existing "manifest.yml" file and the GCP labs: 
# https://github.com/GoogleCloudPlatform/software-delivery-workshop/tree/main/labs/cloudrun-progression

# Default Values
substitutions:
  _TEAM: r2d2             # Used as a Repo in the Artifact Registry
  _APPLICATION_NAME: java-11-hw 
  _APPLICATION_RUNTIME_VERSION: "17"
  _REGION: us-central1
  _AUTHENTICATION: "--allow-unauthenticated"
  _TAG: $SHORT_SHA        # $SHORT_SHA defined for builds invoked by triggers
  _IMAGE_NAME: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_TEAM}/${_APPLICATION_NAME}:${_TAG}'
# fixed substitutions as per advice in:
# https://stackoverflow.com/questions/73176741/google-cloud-build-with-pack-and-secrets-manager-not-accessing-environment-varia

options:
  substitution_option: 'ALLOW_LOOSE'
  dynamic_substitutions: true
steps:

### Build
  - id: "build image from source"
    name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      pack build $_IMAGE_NAME \
        --builder=gcr.io/buildpacks/builder \
        --env=GOOGLE_RUNTIME_VERSION=$_APPLICATION_RUNTIME_VERSION \
        --path . \
        --network cloudbuild

### Test
  - id: "run tests"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: 
      - '-c'
      - |
          echo "No tests to run at this time."

### Deploy
  - id: "deploy image as a branch-named app"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: 
      - '-c'
      - |
          gcloud run deploy $_APPLICATION_NAME $_AUTHENTICATION \
            --platform managed \
            --project $PROJECT_ID \
            --region $_REGION \
            --image $_REGION-docker.pkg.dev/$PROJECT_ID/$_TEAM/$_APPLICATION_NAME:$_TAG


images:
- '$_IMAGE_NAME'
