# Losely based on the existing "manifest.yml" file and the GCP labs: 
# https://github.com/GoogleCloudPlatform/software-delivery-workshop/tree/main/labs/cloudrun-progression
#
# Implemented using workaround for 'build with pack and secrets manager not accessing environment variables' as per:
# https://stackoverflow.com/questions/73176741/google-cloud-build-with-pack-and-secrets-manager-not-accessing-environment-varia

# Default Values
substitutions:
  _TEAM: r2d2                           # Used as a Repo in the Artifact Registry
  _APPLICATION_NAME: java-11-hw 
  _APPLICATION_RUNTIME_VERSION: "17"
  _REGION: us-central1

  _AUTHENTICATION: "--allow-unauthenticated"
  _IMAGE_NAME: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_TEAM}/${_APPLICATION_NAME}"
  _TAG: ${SHORT_SHA:-"shell-run"}       # $SHORT_SHA defined when invoked by triggers
  _BRANCH_NAME: ${BRANCH_NAME:-"demo"}  # $BRANCH_NAME defined when invoked by triggers

# Allow dynamic variable substitutions
options:
  dynamic_substitutions: true

# Start the build with the following
steps:

### Build
  - id: "build image from source"
    name: "gcr.io/k8s-skaffold/pack"
    entrypoint: "sh"
    args:
    - '-c'
    - |
      pack build ${_IMAGE_NAME} \
        --builder=gcr.io/buildpacks/builder \
        --env=GOOGLE_RUNTIME_VERSION=${_APPLICATION_RUNTIME_VERSION} \
        --path . \
        --network cloudbuild

### Tag and Push
  - id: "tag and push the image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args: 
      - '-c'
      - |
          docker tag ${_IMAGE_NAME} ${_IMAGE_NAME}:${_TAG} && \
          docker push ${_IMAGE_NAME}:${_TAG}

### Test
  - id: "run tests"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: 
      - '-c'
      - |
          echo "No tests to run at this time."

### Deploy
# Service name cannot exceed 63 characters, pulse it can contain only letters, numbers, and hyphens
  - id: "deploy image as a branch-named app"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: 
      - '-c'
      - |
          set -e  # Exit on error
          app=$(echo ${_APPLICATION_NAME}-${_BRANCH_NAME} \
            | sed 's/[^a-zA-Z0-9-]/-/g' | cut -c1-63)
          gcloud run deploy ${app} ${_AUTHENTICATION} \
            --platform managed \
            --project $PROJECT_ID \
            --region ${_REGION} \
            --image ${_IMAGE_NAME}:${_TAG}

images:
- ${_IMAGE_NAME}
